# Generated by Django 4.2.3 on 2023-08-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="catagory", new_name="category",
        ),
    ]
